### ISSUE TITLE
errors when compile dpdk in a new compiled kernel

### ISSUE THREAD

**Issue by Fierralin** [eunyoung14/mtcp#46]
We met an unsolvable problem. 
At first we had to run mtcp on a Redhat 6.2 machine whose kernel version was 2.6.32-220.el6.x86_64. We compiled a new kernel version 3.2.78. Then we met the problem. 

When we tried to use the former mtcp version with dpdk-2.1.0, we met these strange problems when compiling dpdk-2.1.0 in it: 

CC [M]  /home/gj/mtcp/dpdk-2.1.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o
In file included from /home/gj/mtcp/dpdk-2.1.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:34:
/home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:378: error: unknown field ‘ndo_fdb_add’ specified in initializer
In file included from /home/gj/mtcp/dpdk-2.1.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:39:
/home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/compat.h:53: error: redefinition of ‘pci_intx_mask_supported’
/home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/compat.h:53: note: previous definition of ‘pci_intx_mask_supported’ was here
/home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/compat.h:76: error: redefinition of ‘pci_check_and_mask_intx’
/home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/compat.h:76: note: previous definition of ‘pci_check_and_mask_intx’ was here
make[10]: **\* [/home/gj/mtcp/dpdk-2.1.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o] Error 1
make[9]: **\* [_module_/home/gj/mtcp/dpdk-2.1.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio] Error 2
make[8]: **\* [sub-make] Error 2
make[7]: **\* [igb_uio.ko] Error 2
make[6]: **\* [igb_uio] Error 2
make[5]: **\* [linuxapp] Error 2
make[4]: **\* [librte_eal] Error 2
make[3]: **\* [lib] Error 2
make[2]: **\* [all] Error 2
make[1]: **\* [x86_64-native-linuxapp-gcc_install] Error 2
make: **\* [install] Error 2

When tried new version with dpdk-2.2.0, error gone with: 

CC [M]  /home/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o
In file included from /home/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:35:
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:218: error: expected declaration specifiers or ‘...’ before ‘netdev_features_t’
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h: In function ‘netdev_set_features’:
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:221: error: ‘features’ undeclared (first use in this function)
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:221: error: (Each undeclared identifier is reported only once
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:221: error: for each function it appears in.)
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h: At top level:
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:229: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘netdev_fix_features’
cc1: warnings being treated as errors
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:283: error: initialization from incompatible pointer type
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:284: error: ‘netdev_fix_features’ undeclared here (not in a function)
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:285: error: unknown field ‘ndo_fdb_add’ specified in initializer
In file included from /home/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:42:
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:66: error: redefinition of ‘pci_intx_mask_supported’
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:66: note: previous definition of ‘pci_intx_mask_supported’ was here
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:89: error: redefinition of ‘pci_check_and_mask_intx’
/home/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:89: note: previous definition of ‘pci_check_and_mask_intx’ was here
make[10]: **\* [/home/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o] Error 1
make[9]: **\* [_module_/home/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio] Error 2
make[8]: **\* [sub-make] Error 2
make[7]: **\* [igb_uio.ko] Error 2
make[6]: **\* [igb_uio] Error 2
make[5]: **\* [linuxapp] Error 2
make[4]: **\* [librte_eal] Error 2
make[3]: **\* [lib] Error 2
make[2]: **\* [all] Error 2
make[1]: **\* [pre_install] Error 2
make: **\* [install] Error 2

In /home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/compat.h, I added
# ifndef COMPAT_H
# define COMPAT_H
# endif

and then solved the redefinition problem. But others are still. 

However, when we turned to the original dpdk version, dpdk-2.1.0-rc4, it succeeded without any error. What's wrong? I thought error goes from the dpdk in mtcp. Who can help me? Thank you!

**Comment by Fierralin** [comment]
In /home/gj/mtcp/dpdk-2.1.0/lib/librte_eal/linuxapp/igb_uio/compat.h, I added
#ifndef COMPAT_H
#define COMPAT_H
#endif
and then solved the redefinition problem.

**Comment by ajamshed** [comment]
Are you still using linux-3.2.78? I'll see if I can get mtcp-dpdk to work for this kernel version. Can you possibly upgrade the kernel to 3.13? We have tested mTCP from linux-3.13~ onwards.

**Comment by Fierralin** [comment]
Oh, we just know that mTCP cannot run on kernels whose version is under 2.6.34. 
We used to work on CentOS with linux-3.10 kernel, that's OK.

**Comment by apassi99** [comment]
Any updates on this? I am facing similar issue with CentOS with version 2.6.32-504.12.2.el6.x86_64

/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:231:1: error: conflicting types for ‘netdev_fix_features’
 netdev_fix_features(struct net_device *netdev, netdev_features_t features)
 ^
In file included from /root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:33:0,
                 from /root/mtcp/mtcp/dpdk-16.04/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:35:
include/linux/netdevice.h:2612:15: note: previous declaration of ‘netdev_fix_features’ was here
 unsigned long netdev_fix_features(unsigned long features, const char *name);
               ^
In file included from /root/mtcp/mtcp/dpdk-16.04/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:35:0:
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:280:9: error: unknown field ‘ndo_set_vf_spoofchk’ specified in initializer
         .ndo_set_vf_spoofchk    = NULL,
         ^
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:283:9: error: unknown field ‘ndo_setup_tc’ specified in initializer
         .ndo_setup_tc           = NULL,
         ^
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:285:9: error: unknown field ‘ndo_set_features’ specified in initializer
         .ndo_set_features  = netdev_set_features,
         ^
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:285:9: error: initialization from incompatible pointer type [-Werror]
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:285:9: error: (near initialization for ‘netdev_ops.ndo_netpoll_cleanup’) [-Werror]
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:286:9: error: unknown field ‘ndo_fix_features’ specified in initializer
         .ndo_fix_features  = netdev_fix_features,
         ^
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:286:9: error: initialization from incompatible pointer type [-Werror]
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:286:9: error: (near initialization for ‘netdev_ops.ndo_set_vf_mac’) [-Werror]
/root/mtcp/mtcp/dpdk-16.04/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:287:9: error: unknown field ‘ndo_fdb_add’ specified in initializer
         .ndo_fdb_add            = NULL,
         ^
cc1: all warnings being treated as errors
make[10]: *** [/root/mtcp/mtcp/dpdk-16.04/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o] Error 1
make[9]: *** [_module_/root/mtcp/mtcp/dpdk-16.04/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio] Error 2
make[8]: *** [sub-make] Error 2
make[7]: *** [igb_uio.ko] Error 2
make[6]: *** [igb_uio] Error 2
make[5]: *** [linuxapp] Error 2
make[4]: *** [librte_eal] Error 2
make[3]: *** [lib] Error 2
make[2]: *** [all] Error 2
make[1]: *** [pre_install] Error 2
make: *** [install] Error 2
------------------------------------------------------------------------------
 RTE_TARGET exported as x86_64-native-linuxapp-gcc
------------------------------------------------------------------------------

Press enter to continue ...

**Comment by ajamshed** [comment]
Your linux kernel is 2.6.32 right? dpdk-16.04 depends on linux kernel >= 2.6.34. We tested mTCP-dpdk from linux-3.13. Can you try mTCP on a kernel >= 3.13?

Alternatively you can try mTCP-psio which should work on linux-2.6.32.

**Comment by apassi99** [comment]
Thanks for your response - So I getting the following error when I try building  mTCP-psio i.e calling make in io_engine/driver.

Here is the error 

make -C /lib/modules/2.6.32-504.12.2.el6.x86_64/build SUBDIRS=/root/mtcp/mtcp/io_engine/driver modules
make[1]: Entering directory `/usr/src/kernels/2.6.32-504.12.2.el6.x86_64'
  CC [M]  /root/mtcp/mtcp/io_engine/driver/ixgbe_ethtool.o
/root/mtcp/mtcp/io_engine/driver/ixgbe_ethtool.c: In function ‘ixgbe_get_sset_count’:
/root/mtcp/mtcp/io_engine/driver/ixgbe_ethtool.c:1040:11: error: ‘ETHTOOL_MAX_NTUPLE_LIST_ENTRY’ undeclared (first use in this function)
   return (ETHTOOL_MAX_NTUPLE_LIST_ENTRY *
           ^
/root/mtcp/mtcp/io_engine/driver/ixgbe_ethtool.c:1040:11: note: each undeclared identifier is reported only once for each function it appears in
/root/mtcp/mtcp/io_engine/driver/ixgbe_ethtool.c:1041:11: error: ‘ETHTOOL_MAX_NTUPLE_STRING_PER_ENTRY’ undeclared (first use in this function)
           ETHTOOL_MAX_NTUPLE_STRING_PER_ENTRY);
           ^
make[2]: *** [/root/mtcp/mtcp/io_engine/driver/ixgbe_ethtool.o] Error 1
make[1]: *** [_module_/root/mtcp/mtcp/io_engine/driver] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.32-504.12.2.el6.x86_64'
make: *** [default] Error 2

**Comment by ajamshed** [comment]
I am not really a big fan of CentOS/Fedora/Redhat flavor linux distros. They tend to change the kernel source that can lead to compilation/compatibility issues. I think this error is arising because  `NETIF_F_NTUPLE ` is enabled for 2.6.32-504.12.2.el6.x86_64. Can you please comment out lines  1039~1041 from `ixgbe_ethtool.c`. Let me know if you still experience any problems.

**Comment by apassi99** [comment]
Sure I will try that. I was able to build it cleanly with dpdk-2.1.0.

**Comment by apassi99** [comment]
Hey even though I got it to compile with version 3.14.110, I was trying to compile the PSIO version on version **2.6.32**. Running install.py gives the following error 

sudo ./install.py 1 1
insmod: error inserting './ps_ixgbe.ko': -1 Invalid parameters
setting xge0...
Cannot get device pause settings: No such device
SIOCSIFADDR: No such device
xge0: unknown interface: No such device
SIOCSIFMTU: No such device
SIOCSIFNETMASK: No such device
SIOCGIFADDR: No such device
SIOCSIFBROADCAST: No such device
OK
Traceback (most recent call last):
  File "./affinity.py", line 35, in <module>
    irq = int(intr.split()[0][:-1])
IndexError: list index out of range

**Comment by ajamshed** [comment]
Can you please share the `dmesg` log? I think `ixgbe.ko` driver is already inserted in your kernel. You first need to remove the driver module from your system. Then try running `install.py` script. _e.g._

```
$ sudo rmmod ixgbe
$ sudo ./install.py 1 1
```

**Comment by vagrus359** [comment]
Same as last error:
```
$ sudo rmmod ixgbe
ERROR: Module ixgbe does not exist in /proc/modules
```

**Comment by ajamshed** [comment]
Which linux kernel are you using?
Can you please share the ``dmesg`` log file?
