### ISSUE TITLE
Can't compile the DPDK

### ISSUE THREAD

**Issue by Mr8** [eunyoung14/mtcp#57]
It's my pleasure you can see this. :)

There's another dpdk on my system and it was compiled without any error. But the dpdk in mtcp occured errors like bellow.
Does some wrong with my OS environment? it's seems that the igb_uio header file uncorrect.

`root@ip-172-17-6-7:/home/zhangbo3/mtcp/dpdk-2.2.0# make install T=x86_64-native-linuxapp-gcc
make[5]: Nothing to be done for `depdirs'.
Configuration done
== Build lib
== Build lib/librte_compat
== Build lib/librte_eal
== Build lib/librte_eal/common
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/igb_uio
  CC [M]  /home/zhangbo3/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o
In file included from /home/zhangbo3/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:35:0:
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:218:48: error: unknown type name ‘netdev_features_t’
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:229:1: error: unknown type name ‘netdev_features_t’
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:229:48: error: unknown type name ‘netdev_features_t’
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:283:30: error: ‘netdev_set_features’ undeclared here (not in a function)
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:284:30: error: ‘netdev_fix_features’ undeclared here (not in a function)
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/igb_uio.h:285:9: error: unknown field ‘ndo_fdb_add’ specified in initializer
In file included from /home/zhangbo3/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:42:0:
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:66:13: error: redefinition of ‘pci_intx_mask_supported’
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:66:13: note: previous definition of ‘pci_intx_mask_supported’ was here
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:89:13: error: redefinition of ‘pci_check_and_mask_intx’
/home/zhangbo3/mtcp/dpdk-2.2.0/lib/librte_eal/linuxapp/igb_uio/compat.h:89:13: note: previous definition of ‘pci_check_and_mask_intx’ was here
make[10]: *** [/home/zhangbo3/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igb_uio.o] Error 1
make[9]: *** [_module_/home/zhangbo3/mtcp/dpdk-2.2.0/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio] Error 2
make[8]: *** [sub-make] Error 2
make[7]: *** [igb_uio.ko] Error 2
make[6]: *** [igb_uio] Error 2
make[5]: *** [linuxapp] Error 2
make[4]: *** [librte_eal] Error 2
make[3]: *** [lib] Error 2
make[2]: *** [all] Error 2
make[1]: *** [pre_install] Error 2
make: *** [install] Error 2`

**Comment by Mr8** [comment]
It's works when I updated my kernel to 3.13.X.. thanks always.
