### ISSUE TITLE
error: implicit declaration of function «pci_enable_msix»

### ISSUE THREAD

**Issue by Sheridan** [eunyoung14/mtcp#157]
I am try to install mtcp to virtualboxed centos7 with 4.13.4-1.el7.elrepo.x86_64 kernel.
```
cd dpdk-16.11
tools/dpdk-setup.sh
```
[13] x86_64-native-linuxapp-gcc

And got this error
```
== Build lib/librte_eal/linuxapp/igb_uio
  CC [M]  /root/mtcp/git/mtcp/dpdk-16.11/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igbuio.o
/root/mtcp/git/mtcp/dpdk-16.11/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igbuio.c: In function «igbuio_pci_probe»:
/root/mtcp/git/mtcp/dpdk-16.11/x86_64-native-linuxapp-gcc/build/lib/librte_eal/linuxapp/igb_uio/igbuio.c:398:3: error: implicit declaration of function «pci_enable_msix» [-Werror=implicit-function-declaration]
```
Tell me please, how can I fix this?

**Comment by ajamshed** [comment]
Hi Sheridan,

I have updated the dpdk driver code. It should now compile on ``linux-4.13.4``. Let me know if you see any other issues. Please note that virtualization support for mTCP, by default, is not enabled. But some users have been able to port mTCP on virtualized environments. Please go through ``issues`` list for details on how to run mTCP apps on virtualized OSes.

**Comment by Oumayma-crypto** [comment]
Hello, I tried to find a detailed solution for this problem, but I found none. Can anyone help me through the steps?
